"""
T4 - Explainer SFT sample builder.

The rows generated by this script are synthetic demonstration rows. Do not put
private campus meter readings, derived kWh/EUI facts, or reviewer traces here.
"""
import json
import pathlib

sp = (
    "你是校園能源助理。你會收到使用者的問題和工具回傳的數據。"
    "\n請根據工具數據回答，格式：結論→依據（數據+來源）→假設與限制→建議下一步。"
    "\n數字必須來自工具回傳值，不可憑空捏造。如果資料不足，明確告知。使用繁體中文。"
)

samples: list[dict] = []
sid = 0


def r(user: str, tool_name: str, tool_result: dict, assistant: str):
    global sid
    sid += 1
    tool_json = json.dumps(tool_result, ensure_ascii=False)
    return {
        "messages": [
            {"role": "system", "content": sp},
            {"role": "user", "content": user},
            {"role": "tool", "name": tool_name, "content": tool_json},
            {"role": "assistant", "content": assistant},
        ],
        "expected_tool": tool_name,
        "difficulty": "explainer",
        "category": "explainer",
        "sample_id": sid,
    }


samples += [
    r(
        "示例建築A一年用多少電？",
        "query_energy_records",
        {
            "status": "ok",
            "records": [
                {
                    "building": "示例建築A",
                    "building_id": "DEMO_A",
                    "annual_kwh": 120000.0,
                    "eui": 80.0,
                    "level": "NORMAL",
                    "area_m2": 1500,
                    "floors": 3,
                }
            ],
        },
        "結論：示例建築A (DEMO_A) 年用電量為 120,000.0 kWh。\n\n依據：工具 query_energy_records 回傳，示例建築A年用電 120,000.0 kWh，EUI 80.0，能耗等級 NORMAL。\n\n假設與限制：此為工具回傳的示例年度資料，若需歷史比較需指定年度區間。\n\n建議：可接著查詢該建築的 EUI、異常時段，或與其他建築比較。",
    ),
    r(
        "全校加起來一年總共用了多少電？",
        "query_energy_records",
        {
            "status": "ok",
            "campus": "DEMO",
            "total_buildings": 3,
            "annual_total_kwh": 500000.0,
            "avg_power_kw": 57.1,
        },
        "結論：示例校區 3 棟建築年總用電量為 500,000.0 kWh。\n\n依據：工具 query_energy_records 回傳，全校年總用電 500,000.0 kWh，平均功率 57.1 kW。\n\n假設與限制：此為彙總數字，未區分各類建築用途。\n\n建議：可再查詢特定建築或年度的細項。",
    ),
    r(
        "示例建築B是什麼等級的耗能建築？",
        "query_energy_records",
        {
            "status": "ok",
            "records": [
                {
                    "building": "示例建築B",
                    "building_id": "DEMO_B",
                    "annual_kwh": 240000.0,
                    "eui": 160.0,
                    "level": "HIGH",
                    "r2": 0.72,
                    "cv_rmse": 14.0,
                }
            ],
        },
        "結論：示例建築B (DEMO_B) 能耗等級為 HIGH。\n\n依據：工具 query_energy_records 回傳，年用電 240,000.0 kWh，EUI 160.0，R2=0.72，等級 HIGH。\n\n假設與限制：HIGH 代表相對基準偏高，但仍需搭配用途、營運時間與設備組成解讀。\n\n建議：建議查詢歷史趨勢並進行異常偵測。",
    ),
    r(
        "全校前五大用電建築",
        "get_top_energy_buildings",
        {
            "status": "ok",
            "top_n": 5,
            "rows": [
                {"name": "示例建築B", "metric": "annual_kwh", "value": 240000.0},
                {"name": "示例建築A", "metric": "annual_kwh", "value": 120000.0},
                {"name": "示例建築C", "metric": "annual_kwh", "value": 90000.0},
            ],
        },
        "結論：目前資料中的前三大用電建築為示例建築B（240,000.0 kWh）、示例建築A（120,000.0 kWh）、示例建築C（90,000.0 kWh）。\n\n依據：工具 get_top_energy_buildings 回傳數據。目前系統只有三筆建築資料，因此 top 5 實際僅 3 筆。\n\n假設與限制：此為示例資料，不代表完整校區排名。\n\n建議：如需完整排名，可先確認資料匯入範圍。",
    ),
    r(
        "2024 跟 2025 全校用電差多少",
        "compare_energy_usage",
        {
            "status": "ok",
            "years": [2024, 2025],
            "scope": "campus",
            "results": [
                {"year": 2024, "value": 480000.0, "metric": "annual_kwh"},
                {"year": 2025, "value": 500000.0, "metric": "annual_kwh"},
            ],
            "delta": 20000.0,
            "delta_pct": 4.17,
        },
        "結論：2025 年全校用電較 2024 年增加 20,000.0 kWh（+4.17%）。\n\n依據：工具 compare_energy_usage 回傳，2024 年 480,000.0 kWh，2025 年 500,000.0 kWh。\n\n假設與限制：此為年度總量比較，未校正天氣、建築數量或使用率變化。\n\n建議：可進一步做 weather-normalized 分析或比較單棟建築貢獻。",
    ),
    r(
        "示例建築B空調調高 2 度會省多少",
        "run_counterfactual_for_building",
        {
            "status": "ok",
            "building_name": "示例建築B",
            "scenario": {"cooling_delta_degC": 2.0},
            "summary": {
                "baseline_kwh": 240000.0,
                "scenario_kwh": 220800.0,
                "saving_kwh": 19200.0,
                "saving_pct": 8.0,
            },
        },
        "結論：示例建築B空調溫度調高 2 度，預估年省電 19,200.0 kWh（約 8.0%）。\n\n依據：工具 run_counterfactual_for_building 模擬結果，基線 240,000.0 kWh，情境 220,800.0 kWh。\n\n假設與限制：此為情境推估，實際節能量受空調佔比、設備效率與使用者行為影響。\n\n建議：可用物理模型驗證，並搭配實測資料做 IPMVP 驗證。",
    ),
]

out = pathlib.Path(__file__).resolve().parent
with open(out / "explainer_sft.jsonl", "w", encoding="utf-8") as f:
    for sample in samples:
        f.write(json.dumps(sample, ensure_ascii=False) + "\n")
print(f"T4 done: {len(samples)} explainer samples -> explainer_sft.jsonl")
